// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction to Physical AI and Humanoid Robotics',
      link: { type: 'doc', id: 'introduction to physical AI and humanoid robotics/overview' },
      items: [{ type: 'autogenerated', dirName: 'introduction to physical AI and humanoid robotics' }],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: { type: 'doc', id: 'ros2/introduction' }, // FIXED
      items: [{ type: 'autogenerated', dirName: 'ros2' }],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin (Gazebo & Unity)',
      link: { type: 'doc', id: 'simulation/gazebo' }, // FIXED
      items: [{ type: 'autogenerated', dirName: 'simulation' }],
    },
    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain (NVIDIA Isaac)',
      link: { type: 'doc', id: 'nvidia_isaac/isaac_sim' }, // FIXED
      items: [{ type: 'autogenerated', dirName: 'nvidia_isaac' }],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      link: { type: 'doc', id: 'vla/vla_pipeline' }, // FIXED
      items: [{ type: 'autogenerated', dirName: 'vla' }],
    },
  ],
};

export default sidebars;